### ISSUE TITLE
Corrupted Packages

### ISSUE THREAD

**Issue by ben-ix** [fasheng/arch-deepin#104]
Hi when trying to download from default mirrror I get many errors

    :: File /var/cache/pacman/pkg/metacity-ubuntu-2.34.13.0ubuntu4.1-7-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/dde-api-2.91.0-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/dde-daemon-2.92.0-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/dde-dock-applets-2.90.1-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/dde-control-center-2.90.3-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/deepin-nautilus-properties-3.14.2-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/dde-workspace-2.90.1-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/gtk-engine-unico-1.0.3.r152-4-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    :: File /var/cache/pacman/pkg/startdde-2.91.0-6-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
    error: failed to commit transaction (invalid or corrupted package (checksum))

When trying to use the alternative mirror I get errors saying 
XYZ exists in both 'deepin-api' and 'dde-api' for many packages

How can I fix this? Thanks

**Comment by fasheng** [comment]
Well, the checksum error is a bug of OBS, I'm afraid you have to install them manually...

And about the conflicts of `deepin-api`([community]) and `dde-api`(OBS/arch-deepin), it is caused by the unfinished work that move Deepin packages to [community]. Simply, please remove `deepin-api` and use `dde-api` instead now.

BTW: `deepin-api` already been removed from `deepin` group, and no package requre it, so it should be harmless unless you installed it manually

**Comment by ben-ix** [comment]
Thanks a lot, issue fixed!

Thank you for all your work bringing deepin to arch.
