### ISSUE TITLE
rebuild of pkgs

### ISSUE THREAD

**Issue by oberon2007** [fasheng/arch-deepin#105]
I see that your pkgs are being rebuild very often and I don't really see any obvious reasons for that - No change in the PKGBUILD and no new commits at linuxdeepin... Are they just automatically rebuild regularly in any case? Since I build the custom manjaro pkgs manually it would be good to know for me, when's the time for me to update them.

**Comment by fasheng** [comment]
In the past, I create a topic to help people to receive news of arch-deepin https://github.com/fasheng/arch-deepin/issues/67. But the old process(generating PKGBUILDs for aur/obs/pkgbuild, and sync changes from obs) is broken since some packages are moved to [community]. And I plan to fix it later.

For manjaro-deepin, I think you don't need to worry about it before `OBS/arch-deepin:2015` is ready, for that DDE packages updated to `2.90.0` should be the last change for `OBS/arch-deepin`.

**Comment by oberon2007** [comment]
thank you.
